local addonName, ns = ...
if type(ns) ~= "table" then
  ns = {}
end

-- Generated by scripts/gen_patch_notes.py from CHANGELOG.md. Do not edit by hand.
local PatchNotes = {
  version = "v2.0.3",
  date = "2026-10-09",
  lines = {
    'The addon now goes by "Whisper Messenger" everywhere: the AddOns list, the window title, the icon tooltips, chat messages and the options.',
    "Whispers can now be about three times longer. Long messages are sent in a few parts and show as one message when your friend also uses Whisper Messenger. Group chats keep the old length.",
    "Trade, General, Local Defense, LFG and your custom channels can now appear as chats. Turn them on under Options > Chats, and they show up in a new Channels tab. Each channel gets its own icon, and General and Local Defense show their zone (like Durotar) at the top of the chat.",
    "Channel chats only count as unread when someone says your name, so a busy Trade chat doesn't bury your other chats. Muting a channel chat also silences the alert for your name.",
    'Channels you read in Whisper Messenger stay in the game\'s own chat too, unless you turn on "Hide channels from default chat" under Options > Chats.',
    'Block players: right-click a player in your contacts and choose Block…, or right-click one of their messages in a group or channel chat and choose Block sender…. You stop seeing anything they send, both here and in the game\'s own chat (say, yell, emotes and channels). You can add a note saying why. A chat with a blocked player shows "Blocked" in red at the top; right-click them and choose Unblock to see their messages again.',
    'Keyword rules hide group and channel messages that contain words you choose (whispers are never filtered). Channel messages they hide are hidden from the game\'s own chat too. They come with ready-made spam filters borrowed from the Global Ignore List addon: "Anal" link spam and Thunderfury links (on), plus Mythic+ and raid sellers, profession sellers, power-leveling sellers, guild recruitment, community recruitment and WTS / WTB / LFW (off until you turn them on). The ready-made filters only apply to channels such as Trade, never to your guild, party or raid.',
    'Make your own keyword rules with Add rule: give the rule a name and its words, and click any rule later to change it. Separate words with / when any one of them should count, and put a word or phrase in "quotes" to match only that whole word or phrase (so "anal" doesn\'t catch canal or analysis). A ready-made filter you remove stays removed until you press Reset to Defaults, which brings them all back and clears your own rules.',
    "Blocking players and keyword rules never hide anything in Mythic+, boss fights or PvP.",
    "Options are split into Behavior, Whispers, Chats and Filters pages, and each page has a small icon next to its name. The new Filters page manages blocked players and keyword rules and starts with a short guide to what each one hides. Point at a blocked player there to see their last blocked message, your note, and how many of their messages were blocked since you logged in.",
    "New option in Appearance: show player names above their messages in their class color, in whispers, group and channel chats, and in the new-message preview next to the messenger icon. On by default; turn it off there if you prefer plain names.",
    'New option in Appearance: Show player levels (off by default). It shows a player\'s level, colored like the quest log by how it compares to yours, at the top of a chat next to their class ("Level 80 Shaman") for Battle.net friends and guild or community members, and before names in group and channel chats ("20:Nergrom"). Offline contacts keep the last level seen. Levels before names show on messages that arrive after you turn the option on. It also shows levels for other players once you\'ve seen them: targeted, moused over, on a nameplate, in your group or friends list, or in /who results. Players you\'ve never seen show no level. When you open or whisper someone whose level is still unknown, the addon looks it up once, quietly.',
    "When someone says your name in a group or channel chat, with or without an @ in front, your name in their message now shows in your class color.",
    "Right-click the top of a conversation (the name or status) to open its menu. For a player, that includes invite to group, ignore and report.",
    "Repeated messages from the same player now show once with a counter (like ×3).",
    "A burst of whispers from one person now plays the alert sound once instead of once per line.",
    'Entering or leaving a Mythic+ dungeon no longer posts "Suspended" and "Resumed" lines in your chat; the window and its icon already show that messages are paused.',
    "The notice shown during Mythic+ and PvP now says messages are paused, not just whispers, since group and channel chats pause too. In a whisper chat it also tells you how to reply right away from the game's own chat.",
    "Uses less CPU, both with the window closed and in busy group chats with it open. Searching your contacts also stays smooth while you type.",
    "Deleting a message request now opens the next one, so the empty Requests page only shows once none are left.",
    "The search box, and the magnifier on the narrow contact list, are hidden on a tab that has no chats to search.",
    'The "Max Messages Per Contact" option is now called "Max Messages Per Chat", since it covers group and channel chats too.',
    "With the Native WoW HUD's Classic style, scrollbars are slimmer: a smaller gold knob with no dark strip behind it, so lists and Options pages keep more room.",
    "Changing the Native WoW HUD style now only sticks if you press Reload UI in the pop-up. Pressing Cancel keeps the style you have now, instead of switching on your next reload.",
    'Fixed: with "Hide whispers from default chat" on, your reply key did nothing if the game\'s "Cast action keybinds on key down" option was turned off.',
    'Fixed: choosing "Whisper" after right-clicking a player\'s name in the window (in guild, group and channel chats, or on a contact) did nothing.',
    'Fixed: right-clicking the name of a guild or group member who isn\'t your Battle.net friend showed a menu without "Whisper".',
    "Fixed: right-clicking a player's name in a group or channel chat now opens that player's menu instead of the chat's own menu.",
    "Fixed: scrolling up through a long chat used a lot of CPU and could slow the game down.",
    "Fixed: after clicking somewhere else, your action bars and other addons' buttons drew on top of the window.",
    "Fixed: opening the window now jumps to the newest unread chat on the tab you're looking at, instead of skipping it when an unread chat on another tab is newer.",
    "Fixed: the Mythic+ pause notice now shows in your game's language instead of always in English.",
    "Fixed: after you accept a message request, the Requests tab no longer keeps showing that chat; it shows its empty page.",
    "Fixed: with the Native WoW HUD on, the tabs under the window are now the same size as the game's own tabs instead of oversized (about twice as wide on Classic game versions), and their unread counts sit on each tab's top corner instead of half hidden behind the window's border.",
    "Fixed: the tabs under the window now always fit its width, even with Requests turned on; a long tab name is shortened and shows in full when you point at it.",
    "Fixed: with the Native WoW HUD on, buttons in Options and pop-ups now light up when you point at them.",
    "Fixed: on Classic game versions, text boxes in pop-ups (starting a whisper, copying a message, editing a filter rule) no longer stick out past the pop-up's edges, and the pop-up no longer gets wider each time it opens.",
    "Fixed: with a large font size, the welcome message no longer runs past the edges of the chat area, and the right edge of Options pages is no longer cut off.",
    "Fixed: with a large font size, the name, status and zone at the top of a chat no longer spill into the messages below, and the paused-in-Mythic+ notice no longer covers the last message.",
    'Fixed: with a large font size, the message request bar above the text box grows to fit its text instead of spilling over the chat, and a long name at the top of a chat is shortened so "(Invite to WM)" stays inside the window.',
  },
}

ns.PatchNotes = PatchNotes

return PatchNotes
