local addonName, ns = ...
if type(ns) ~= "table" then
  ns = {}
end

-- Generated by scripts/gen_patch_notes.py from CHANGELOG.md. Do not edit by hand.
local PatchNotes = {
  version = "v1.4.2",
  date = "2026-09-11",
  lines = {
    'Added live typing indicators: when a friend who also uses WhisperMessenger is writing to you, their contact row and the conversation header show "typing…" in green until they send or stop.',
    'Added "Seen" receipts: once a friend who also uses WhisperMessenger has your conversation open, your latest sent messages show a green "Seen" next to the timestamp. Contacts who run the addon are labelled "Uses WhisperMessenger" in the conversation header.',
    'Added two Behavior settings, "Share typing status" and "Send read receipts", both on by default. Turn them off to stop sharing your own typing and read activity. Nothing is ever sent to players without the addon, and both pause during Mythic+ and other restricted content.',
    "Fixed: reduced CPU use while the messenger is open with Battle.net contacts, and stopped typing and read updates from refreshing the window when nothing has changed.",
    'Fixed: Battle.net friends who are fully offline no longer show as "Online (App)" in the contact list and conversation header. Friends who are only in the Battle.net app now show "Online (App)" instead of plain "Online".',
    "Contacts now show where a Battle.net friend or guild/community member currently is (zone, arena, or dungeon), in a dimmed line under their name in the contact list and in the conversation header, like the Battle.net friends list.",
    'Fixed: Battle.net friends who are also logged into the Battle.net app or another Blizzard game now show their WoW character, class, faction, and zone again, and no longer appear as "Away" when they are online in WoW.',
    "Fixed: when a Battle.net friend is offline, their class icon in the contact list and the class shown in the conversation header no longer disagree, and the header no longer shows a stale zone for them.",
    "Fixed: whispers that arrived while the messenger was open no longer pop up as a preview on the widget a few seconds after you close the window.",
    "Fixed: after replying to a whisper in the default chat during a Mythic+ run, pressing Enter once the run is over no longer keeps opening the messenger to that person, so you can type in Say and General again.",
    "Fixed: shift-clicking a player name or link in chat while typing in the messenger no longer inserts it several times; the name now appears once.",
    "Fixed: hovering a profession link in a conversation no longer opens the profession window; it now opens only when you click the link.",
    "Fixed: after you click outside the messenger, the window no longer slips behind the pet bar, action bars, or other bars at the bottom of the screen.",
    "Fixed: the floating widget icon and its incoming-message preview now stay above bags, action bars, and other windows.",
  },
}

ns.PatchNotes = PatchNotes

return PatchNotes
