#!/usr/bin/env python3
"""Bake the latest CHANGELOG.md release section into Core/PatchNotes.lua.

The addon shows these lines in its in-game "What's New" dialog, so they must
ship inside the packaged addon rather than being read from CHANGELOG.md.

Usage:
    python scripts/gen_patch_notes.py
    python scripts/gen_patch_notes.py --version v1.4.0

With --version the script refuses to write unless the top versioned section
of CHANGELOG.md matches, which keeps a release from shipping stale notes.
"""

import argparse
import os
import re
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHANGELOG_PATH = os.path.join(PROJECT_ROOT, "CHANGELOG.md")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "Core", "PatchNotes.lua")

# "## [1.4.0] - 2026-08-31" or "## [1.4.0]". "## [Unreleased]" never matches.
SECTION_PATTERN = re.compile(r"^## \[(\d+\.\d+\.\d+)\](?: - (\S+))?\s*$")


def parse_latest_section(text):
    """Return (version, date, lines) for the first versioned section."""
    version = None
    date = None
    lines = []

    for raw_line in text.splitlines():
        if version is None:
            match = SECTION_PATTERN.match(raw_line)
            if match:
                version, date = match.group(1), match.group(2)
            continue

        if raw_line.startswith("## "):
            break

        if raw_line.startswith("- "):
            bullet = raw_line[2:].strip()
            if bullet:
                lines.append(bullet)

    return version, date, lines


def escape_lua(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_lua(version, date, lines):
    body = ['local addonName, ns = ...', 'if type(ns) ~= "table" then', "  ns = {}", "end", ""]
    body.append("-- Generated by scripts/gen_patch_notes.py from CHANGELOG.md. Do not edit by hand.")
    body.append("local PatchNotes = {")
    body.append('  version = "v%s",' % escape_lua(version))
    if date:
        body.append('  date = "%s",' % escape_lua(date))
    body.append("  lines = {")
    for line in lines:
        body.append('    "%s",' % escape_lua(line))
    body.append("  },")
    body.append("}")
    body.append("")
    body.append("ns.PatchNotes = PatchNotes")
    body.append("")
    body.append("return PatchNotes")
    return "\n".join(body) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate Core/PatchNotes.lua from CHANGELOG.md")
    parser.add_argument("--version", help="Expected release version (with or without a leading v)")
    args = parser.parse_args()

    try:
        with open(CHANGELOG_PATH, "r", encoding="utf-8") as handle:
            text = handle.read()
    except OSError as error:
        print("Error: could not read %s: %s" % (CHANGELOG_PATH, error), file=sys.stderr)
        return 1

    version, date, lines = parse_latest_section(text)

    if version is None:
        print("Error: no versioned '## [x.y.z]' section found in CHANGELOG.md", file=sys.stderr)
        return 1

    if not lines:
        print("Error: section '## [%s]' in CHANGELOG.md has no '- ' bullet lines" % version, file=sys.stderr)
        return 1

    if args.version:
        expected = args.version.lstrip("v")
        if expected != version:
            print(
                "Error: requested version v%s but the top CHANGELOG.md section is v%s.\n"
                "       Add a '## [%s] - <date>' section with this release's notes first." % (expected, version, expected),
                file=sys.stderr,
            )
            return 1

    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_lua(version, date, lines))

    print("Wrote %s (v%s, %d line%s)" % (OUTPUT_PATH, version, len(lines), "" if len(lines) == 1 else "s"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
